### PR TITLE
Fix formatting issue in Readme

### PR DESCRIPTION
**Pull request by stackotter**
Hi Joakim, this reusable plugin manager prototype you've made is very cool! I'm glad my plugin manager implementation could help out :)

I just noticed a formatting issue in the readme that messed up one of the code blocks and thought I should fix it (that's what this PR is for).

### CODE REVIEW

**Comment by hassila** [comment]
Whoops, thanks for the fix - and for the inspiration to finally get this done, I've had a handful of links on the plugin theme and ragged my feet... Hope to be able to do something cool with the api compatibility checking that comes with 5.6!

**Comment by stackotter** [comment]
The API compatibility checker certainly sounds very useful! Would you happen to have a link to the pitch for it?

**Comment by hassila** [comment]
@stackotter 

Well, no pitch available as far as I know, it is fairly little known but has been around for a couple of years and recently integrated into SPM (using the api-digester from swift) - I’ve stumbled upon it and hope it will get more exposure going forward (ping @tomdoron - maybe a short blog entry for swift.org?! - it's great stuff), truly useful I think.

Here are some random links how I found it:

Integrated in SPM:
https://github.com/apple/swift-package-manager/pull/3485

https://forums.swift.org/t/using-swift-api-digester/22956
https://github.com/apple/swift-nio/issues/965
https://github.com/apple/swift-package-manager/pull/3359
https://github.com/apple/swift/blob/dd8b405dfbda027b8942e406ba67d95e98182b3e/tools/swift-api-digester/swift-api-digester.cpp

The output looks like this with 5.6-dev trying a couple of changes:
```
jocke@linux ~/s/swift-plugin (main)> swift package diagnose-api-breaking-changes 0.1.0
[4/4] Build complete!

1 breaking change detected in Plugin:
  💔 API breakage: func PluginFactory.x() has been added as a protocol requirement
jocke@linux ~/s/swift-plugin (main) [1]> nano Sources/Plugin/Plugin.swift
jocke@linux ~/s/swift-plugin (main)> swift package diagnose-api-breaking-changes 0.1.0
[4/4] Build complete!

1 breaking change detected in Plugin:
  💔 API breakage: func PluginFactory.create() has been renamed to func create(_:)
jocke@linux ~/s/swift-plugin (main) [1]> swift --version
Swift version 5.6-dev (LLVM 3647999e44ce50a, Swift 22aa3c5dbe4e319)
Target: aarch64-unknown-linux-gnu
jocke@linux ~/s/swift-plugin (main)> 
```

**Comment by stackotter** [comment]
That looks super useful! I'll definitely try and integrate that into my plugin api and build tool in some form. It even looks handy for just figuring out regular semver stuff.

**Pull request merged**
